services:
  api:
    build: .
    container_name: fastapi_training
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ekos-network

networks:
  ekos-network:
    external: true